version: "2"
services:
  rocket.chat:
    image: akisys/rocket.chat
    environment:
      MONGO_SERVICE_ID: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: rocketchat
      MONGO_REPLSET: mongodb-rs1
  mongodb:
    image: akisys/mongodb-cluster:3.4
    environment:
      MONGO_SERVICE_ID: mongodb
      MONGO_PORT: 27017
      MONGO_STARTUP: mongodb
      MONGO_REPLSET: mongodb-rs1

